name: auto-update

on:
  workflow_dispatch:
    inputs:
      git_commit:
        required: false
  schedule:
    - cron: "0 8 * * 0"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_TOKEN }}

      - name: Get latest version
        id: cheribuild-version
        run: |
          if [ -n "${{ github.event.inputs.git_commit }}" ]; then
            git clone https://github.com/CTSRD-CHERI/cheribuild.git
            cd cheribuild
            GIT_COMMIT="${{ github.event.inputs.git_commit }}"
          else
            git clone https://github.com/CTSRD-CHERI/cheribuild.git
            cd cheribuild
            GIT_COMMIT="$(git rev-parse --short HEAD)"
          fi

          DATE="$(git show -s --format=%cd --date=local --date=format:'%Y.%m.%d' ${GIT_COMMIT})"
          echo "tag=v${DATE}-${GIT_COMMIT}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.5.0
        id: check-tag
        with: 
          tag: ${{ steps.cheribuild-version.outputs.tag }}
          repo: 'cocoa-xu/cheribuild'
      
      - name: Update if tag not exists
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.cheribuild-version.outputs.tag }}
          git push origin ${{ steps.cheribuild-version.outputs.tag }}
